server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location /api/ {
        proxy_pass http://core-api:8000/;
    }
    location /tracking/ {
        proxy_pass http://mock-tracking:8081/;
    }
    location /stats/ {
        proxy_pass http://mock-analytics:8082/;
    }
}