// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repositories

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type TrackStatus string

const (
	TrackStatusPending    TrackStatus = "pending"
	TrackStatusProcessing TrackStatus = "processing"
	TrackStatusReady      TrackStatus = "ready"
	TrackStatusFailed     TrackStatus = "failed"
)

func (e *TrackStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TrackStatus(s)
	case string:
		*e = TrackStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TrackStatus: %T", src)
	}
	return nil
}

type NullTrackStatus struct {
	TrackStatus TrackStatus
	Valid       bool // Valid is true if TrackStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTrackStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TrackStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TrackStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTrackStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TrackStatus), nil
}

type Track struct {
	ID                pgtype.UUID
	Artist            string
	Title             string
	OriginalFilename  string
	OriginalObjectKey string
	OriginalSize      int64
	Status            TrackStatus
	UploadedAt        pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	HlsPlaylistKey    pgtype.Text
}
