// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_tracks.sql

package repositories

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTrack = `-- name: CreateTrack :one
INSERT INTO tracks (
  artist,
  title,
  original_filename,
  original_object_key,
  original_size,
  status
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
RETURNING id, artist, title, original_filename, original_object_key, original_size, status, uploaded_at, updated_at, hls_playlist_key
`

type CreateTrackParams struct {
	Artist            string
	Title             string
	OriginalFilename  string
	OriginalObjectKey string
	OriginalSize      int64
	Status            TrackStatus
}

func (q *Queries) CreateTrack(ctx context.Context, arg CreateTrackParams) (Track, error) {
	row := q.db.QueryRow(ctx, createTrack,
		arg.Artist,
		arg.Title,
		arg.OriginalFilename,
		arg.OriginalObjectKey,
		arg.OriginalSize,
		arg.Status,
	)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Artist,
		&i.Title,
		&i.OriginalFilename,
		&i.OriginalObjectKey,
		&i.OriginalSize,
		&i.Status,
		&i.UploadedAt,
		&i.UpdatedAt,
		&i.HlsPlaylistKey,
	)
	return i, err
}

const deleteTrackByID = `-- name: DeleteTrackByID :exec
DELETE FROM tracks
WHERE id = $1
`

func (q *Queries) DeleteTrackByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTrackByID, id)
	return err
}

const getTrackByID = `-- name: GetTrackByID :one
SELECT id, artist, title, original_filename, original_object_key, original_size, status, uploaded_at, updated_at, hls_playlist_key
FROM tracks
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTrackByID(ctx context.Context, id pgtype.UUID) (Track, error) {
	row := q.db.QueryRow(ctx, getTrackByID, id)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Artist,
		&i.Title,
		&i.OriginalFilename,
		&i.OriginalObjectKey,
		&i.OriginalSize,
		&i.Status,
		&i.UploadedAt,
		&i.UpdatedAt,
		&i.HlsPlaylistKey,
	)
	return i, err
}

const listReadyTracks = `-- name: ListReadyTracks :many
SELECT id, artist, title, original_filename, original_object_key, original_size, status, uploaded_at, updated_at, hls_playlist_key
FROM tracks
WHERE status = 'ready'
ORDER BY uploaded_at DESC
`

func (q *Queries) ListReadyTracks(ctx context.Context) ([]Track, error) {
	rows, err := q.db.Query(ctx, listReadyTracks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.Artist,
			&i.Title,
			&i.OriginalFilename,
			&i.OriginalObjectKey,
			&i.OriginalSize,
			&i.Status,
			&i.UploadedAt,
			&i.UpdatedAt,
			&i.HlsPlaylistKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracks = `-- name: ListTracks :many
SELECT id, artist, title, original_filename, original_object_key, original_size, status, uploaded_at, updated_at, hls_playlist_key
FROM tracks
ORDER BY uploaded_at DESC
`

func (q *Queries) ListTracks(ctx context.Context) ([]Track, error) {
	rows, err := q.db.Query(ctx, listTracks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.Artist,
			&i.Title,
			&i.OriginalFilename,
			&i.OriginalObjectKey,
			&i.OriginalSize,
			&i.Status,
			&i.UploadedAt,
			&i.UpdatedAt,
			&i.HlsPlaylistKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracksByStatus = `-- name: ListTracksByStatus :many
SELECT id, artist, title, original_filename, original_object_key, original_size, status, uploaded_at, updated_at, hls_playlist_key
FROM tracks
WHERE status = $1
ORDER BY uploaded_at DESC
`

func (q *Queries) ListTracksByStatus(ctx context.Context, status TrackStatus) ([]Track, error) {
	rows, err := q.db.Query(ctx, listTracksByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.Artist,
			&i.Title,
			&i.OriginalFilename,
			&i.OriginalObjectKey,
			&i.OriginalSize,
			&i.Status,
			&i.UploadedAt,
			&i.UpdatedAt,
			&i.HlsPlaylistKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTrackFailed = `-- name: MarkTrackFailed :one
UPDATE tracks
SET status = 'failed',
    updated_at = NOW()
WHERE id = $1
RETURNING id, artist, title, original_filename, original_object_key, original_size, status, uploaded_at, updated_at, hls_playlist_key
`

func (q *Queries) MarkTrackFailed(ctx context.Context, id pgtype.UUID) (Track, error) {
	row := q.db.QueryRow(ctx, markTrackFailed, id)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Artist,
		&i.Title,
		&i.OriginalFilename,
		&i.OriginalObjectKey,
		&i.OriginalSize,
		&i.Status,
		&i.UploadedAt,
		&i.UpdatedAt,
		&i.HlsPlaylistKey,
	)
	return i, err
}

const markTrackProcessing = `-- name: MarkTrackProcessing :one
UPDATE tracks
SET status = 'processing',
    updated_at = NOW()
WHERE id = $1
RETURNING id, artist, title, original_filename, original_object_key, original_size, status, uploaded_at, updated_at, hls_playlist_key
`

func (q *Queries) MarkTrackProcessing(ctx context.Context, id pgtype.UUID) (Track, error) {
	row := q.db.QueryRow(ctx, markTrackProcessing, id)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Artist,
		&i.Title,
		&i.OriginalFilename,
		&i.OriginalObjectKey,
		&i.OriginalSize,
		&i.Status,
		&i.UploadedAt,
		&i.UpdatedAt,
		&i.HlsPlaylistKey,
	)
	return i, err
}

const markTrackReady = `-- name: MarkTrackReady :one
UPDATE tracks
SET status = 'ready',
    hls_playlist_key = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, artist, title, original_filename, original_object_key, original_size, status, uploaded_at, updated_at, hls_playlist_key
`

type MarkTrackReadyParams struct {
	ID             pgtype.UUID
	HlsPlaylistKey pgtype.Text
}

func (q *Queries) MarkTrackReady(ctx context.Context, arg MarkTrackReadyParams) (Track, error) {
	row := q.db.QueryRow(ctx, markTrackReady, arg.ID, arg.HlsPlaylistKey)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Artist,
		&i.Title,
		&i.OriginalFilename,
		&i.OriginalObjectKey,
		&i.OriginalSize,
		&i.Status,
		&i.UploadedAt,
		&i.UpdatedAt,
		&i.HlsPlaylistKey,
	)
	return i, err
}
